<?php

namespace Tests\Browser;

use App\Models\People\User;
use Illuminate\Foundation\Testing\DatabaseTruncation;
use Illuminate\Support\Str;
use Laravel\Dusk\Browser;
use Tests\DuskTestCase;

class LoginTest extends DuskTestCase
{
    use DatabaseTruncation;

    /** @var User */
    protected $testUser;

    /** @var string  */
    protected $password;

    /**
     * Test if the login screen is visible and contains the necessary form
     */
    public function testLoginScreenVisible(): void
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/')
                    ->assertSee(config('app.name'))
                    ->assertSee('E-Mailadresse')
                    ->assertSee('Passwort')
                    ->assertSee('Anmelden');
        });
    }

    public function testLoginWorks(): void
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/')
            ->type('email', $this->testUser->email)
                ->type('password', $this->password)
                ->waitForReload(function (Browser $browser) {
                   $browser->press('Anmelden');
                })->assertRouteIs('home');
        });
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->password = Str::random(16);
        $this->testUser = User::factory()->create(['password' => $this->password]);
    }


}
