<?php
/*
 * Pfarrplaner
 *
 * @package Pfarrplaner
 * @author Christoph Fischer <chris@toph.de>
 * @copyright (c) Christoph Fischer, https://christoph-fischer.org
 * @license https://www.gnu.org/licenses/gpl-3.0.txt GPL 3.0 or later
 * @link https://codeberg.org/pfarr.tools/pfarrplaner
 * @version git: $Id$
 *
 * Sponsored by: Evangelischer Kirchenbezirk Balingen, https://www.kirchenbezirk-balingen.de
 *
 * Pfarrplaner is based on the Laravel framework (https://laravel.com).
 * This file may contain code created by Laravel's scaffolding functions.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Tests;

use App\Models\People\User;
use App\Services\RoleService;
use Database\Seeders\RoleSeeder;
use Illuminate\Foundation\Testing\DatabaseTruncation;
use Illuminate\Support\Str;
use Laravel\Dusk\Browser;

abstract class AbstractModelBrowserTest extends DuskTestCase
{

    use DatabaseTruncation;

    protected $modelclass;
    protected $seeder = RoleSeeder::class;

    /**
     * Test, if an Admin module is present
     * @test
     * @return void
     */
    public function testHasAdminModule()
    {
        if ($this->skipTestIfNoAdminModule()) return;
        $this->browse(function (Browser $browser) {
            $browser->loginAs($this->testUser)->visit('/admin')
                ->assertSee('Kirchengemeinden');
        });


    }

    /**
     * @test
     * @return void
     */
    public function testNewRecordIsVisibleInIndex()
    {
        if ($this->skipTestIfNoAdminModule()) return;
        $existing = ($this->modelClass)::factory()->create();
        $this->assertTrue($this->testUser->can('update', $existing));
        $this->browse(function (Browser $browser) use ($existing) {
            $browser->loginAs($this->testUser, 'web')->visit(($this->modelClass)::getSingleRoute('web', 'index'))
                ->screenshot('cityIndex')
                ->assertSee($existing->label);
        });

    }


    /**
     * Skip the test, if this model has no separate admin module
     * @return bool
     */
    protected function skipTestIfNoAdminModule(): bool {
        $config = ($this->modelClass)::getAdminModuleConfig();
        if ($config == []) {
            $this->assertTrue();
            return true;
        }
        return false;
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->testUser = User::factory()->create();
        $this->testUser->assignRole(RoleService::ROLE_SUPER_ADMIN);
    }




}
